language: python
python:
  - "2.6"
env:
  - TOX_ENV=py26
  - TOX_ENV=pep8
  #- TOX_ENV=cover
before_install:
  - pip install tox --use-mirrors
script: 
  - tox -e $TOX_ENV

after_success:
  - if [ "x$TOX_ENV" = 'xcover' ]; then coveralls; fi